spring:
  application:
    name: product-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers:
      - "localhost:9092"
    consumer:
      group-id: products
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: products

server:
  port: 8001
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: false

logging:
  level:
    org.springframework.web: INFO
